NumPy - Numerical Python

In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.2'

In [6]:
list_array_a = [2,4,6,8]
list_array_b = [2,2,1,1]

print ("array a from list:", list_array_a)
print ("array a from list:", list_array_b)

array a from list: [2, 4, 6, 8]
array a from list: [2, 2, 1, 1]


In [7]:
np_array_a1 = np.array(list_array_a)
print(np_array_a1)

np_array_b1 = np.array(list_array_b)
print(np_array_b1)

[2 4 6 8]
[2 2 1 1]


In [9]:
np_array_a1, np_array_b1

(array([2, 4, 6, 8]), array([2, 2, 1, 1]))

In [10]:
print(np_array_a1[2:])
print(np_array_b1[:2])

[6 8]
[2 2]


In [11]:
np_array_a2 = np.array([[1,2,3], [4,5,6]])
np_array_a2

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
np_array_b2 = np.array([[.1,.2,.3], [.4,.5,.6]])
np_array_b2

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6]])

In [15]:
print(np_array_a1.shape)
print(np_array_a2.shape)
print(np_array_b1.shape)
print(np_array_b2.shape)

np_array_a14 = np.array([[10,20,30,40]])
np_array_a41 = np.array([[5], [10], [15], [20]])
print(np_array_a14, np_array_a14.shape)
print(np_array_a41, np_array_a41.shape)

(4,)
(2, 3)
(4,)
(2, 3)
[[10 20 30 40]] (1, 4)
[[ 5]
 [10]
 [15]
 [20]] (4, 1)


In [17]:
np_array_zeros1 = np.zeros(5)
np_array_zeros2 = np.zeros((3,4))

print(np_array_zeros1)
print(np_array_zeros2)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
zeros = np.zeros((100,100))
print(zeros)
print(zeros.shape)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(100, 100)


In [20]:
np_array_ones1 = np.ones(10)
np_array_ones2 = np.ones((10,3))

print(np_array_ones1)
print(np_array_ones2)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [24]:
print(np_array_zeros1.ndim)
print(np_array_zeros2.ndim)

1
2


In [26]:
print(np_array_a14.size)
print(np_array_ones2.size)

4
30


In [29]:
np_arange10 = np.arange(10)
print(np_arange10)

[0 1 2 3 4 5 6 7 8 9]


In [30]:
np_arange20 = np.arange(0,20,2)
print(np_arange20)

[ 0  2  4  6  8 10 12 14 16 18]


In [31]:
np_arange_desc = np.arange(50,0,-5)
print(np_arange_desc)

[50 45 40 35 30 25 20 15 10  5]


In [32]:
np.append(np_arange10, np_arange20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  0,  2,  4,  6,  8, 10, 12,
       14, 16, 18])

In [33]:
np.append(np.append(np_arange10, np_arange20), np_arange_desc)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  0,  2,  4,  6,  8, 10, 12,
       14, 16, 18, 50, 45, 40, 35, 30, 25, 20, 15, 10,  5])

In [34]:
arr = np.append(np_arange10, np_arange20)
np.append(arr, np_arange_desc)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  0,  2,  4,  6,  8, 10, 12,
       14, 16, 18, 50, 45, 40, 35, 30, 25, 20, 15, 10,  5])

In [35]:
np.append(np_array_a2, np_array_b2)

array([1. , 2. , 3. , 4. , 5. , 6. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6])

In [36]:
np.append(np_array_a2, np_array_b2, axis=0)

array([[1. , 2. , 3. ],
       [4. , 5. , 6. ],
       [0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6]])

In [37]:
np.append(np_array_a2, np_array_b2, axis=1)

array([[1. , 2. , 3. , 0.1, 0.2, 0.3],
       [4. , 5. , 6. , 0.4, 0.5, 0.6]])

In [38]:
np.append(np_array_a2, np_array_zeros2)

array([1., 2., 3., 4., 5., 6., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

In [44]:
np.sort(np_arange_desc)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [45]:
np_arange_desc

array([50, 45, 40, 35, 30, 25, 20, 15, 10,  5])

In [47]:
np_array_a2b2 = np.append(np_array_a2, np_array_b2, axis=0)
print(np_array_a2b2)

[[1.  2.  3. ]
 [4.  5.  6. ]
 [0.1 0.2 0.3]
 [0.4 0.5 0.6]]


In [48]:
np.sort(np_array_a2b2, axis=0)

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6],
       [1. , 2. , 3. ],
       [4. , 5. , 6. ]])

In [49]:
np.sort(np_array_a2b2, axis=1)

array([[1. , 2. , 3. ],
       [4. , 5. , 6. ],
       [0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6]])

In [50]:
np_array_a3 = np.array(
    [
        [
            [9,3,1,5],
            [1,3,2,3],
            [4,10,3,2],
        ],
        [
            [19,3,1,50],
            [11,3,12,13],
            [4,10,3,2],
        ],
        [
            [100,3,1,5],
            [1,3,2,3],
            [4,10,3,2],
        ]      
    ]
)

print(np_array_a3)
print("shape:", np_array_a3.shape)
print("ndim:", np_array_a3.ndim)
print("size:", np_array_a3.size)

[[[  9   3   1   5]
  [  1   3   2   3]
  [  4  10   3   2]]

 [[ 19   3   1  50]
  [ 11   3  12  13]
  [  4  10   3   2]]

 [[100   3   1   5]
  [  1   3   2   3]
  [  4  10   3   2]]]
shape: (3, 3, 4)
ndim: 3
size: 36


In [52]:
type(np_array_a3)

numpy.ndarray

In [53]:
#di array bisa reshape

In [56]:
np.reshape(np_array_a3, (6,6))

array([[  9,   3,   1,   5,   1,   3],
       [  2,   3,   4,  10,   3,   2],
       [ 19,   3,   1,  50,  11,   3],
       [ 12,  13,   4,  10,   3,   2],
       [100,   3,   1,   5,   1,   3],
       [  2,   3,   4,  10,   3,   2]])

In [57]:
np_array_a3.reshape((6,6))

array([[  9,   3,   1,   5,   1,   3],
       [  2,   3,   4,  10,   3,   2],
       [ 19,   3,   1,  50,  11,   3],
       [ 12,  13,   4,  10,   3,   2],
       [100,   3,   1,   5,   1,   3],
       [  2,   3,   4,  10,   3,   2]])

In [58]:
np_array_a3.reshape((4,4)) #--> harus memperhatikan sizenya, sebelumnya 36

ValueError: cannot reshape array of size 36 into shape (4,4)

In [59]:
np_array_a3.reshape((3,3,2,2))

array([[[[  9,   3],
         [  1,   5]],

        [[  1,   3],
         [  2,   3]],

        [[  4,  10],
         [  3,   2]]],


       [[[ 19,   3],
         [  1,  50]],

        [[ 11,   3],
         [ 12,  13]],

        [[  4,  10],
         [  3,   2]]],


       [[[100,   3],
         [  1,   5]],

        [[  1,   3],
         [  2,   3]],

        [[  4,  10],
         [  3,   2]]]])

In [60]:
np_array_a3.reshape((3,3,2,2,1)) #--> 5 dimensi

array([[[[[  9],
          [  3]],

         [[  1],
          [  5]]],


        [[[  1],
          [  3]],

         [[  2],
          [  3]]],


        [[[  4],
          [ 10]],

         [[  3],
          [  2]]]],



       [[[[ 19],
          [  3]],

         [[  1],
          [ 50]]],


        [[[ 11],
          [  3]],

         [[ 12],
          [ 13]]],


        [[[  4],
          [ 10]],

         [[  3],
          [  2]]]],



       [[[[100],
          [  3]],

         [[  1],
          [  5]]],


        [[[  1],
          [  3]],

         [[  2],
          [  3]]],


        [[[  4],
          [ 10]],

         [[  3],
          [  2]]]]])

In [61]:
np_array_a3.reshape((3,3,2,2,1,1)) #-->6dimensi

array([[[[[[  9]],

          [[  3]]],


         [[[  1]],

          [[  5]]]],



        [[[[  1]],

          [[  3]]],


         [[[  2]],

          [[  3]]]],



        [[[[  4]],

          [[ 10]]],


         [[[  3]],

          [[  2]]]]],




       [[[[[ 19]],

          [[  3]]],


         [[[  1]],

          [[ 50]]]],



        [[[[ 11]],

          [[  3]]],


         [[[ 12]],

          [[ 13]]]],



        [[[[  4]],

          [[ 10]]],


         [[[  3]],

          [[  2]]]]],




       [[[[[100]],

          [[  3]]],


         [[[  1]],

          [[  5]]]],



        [[[[  1]],

          [[  3]]],


         [[[  2]],

          [[  3]]]],



        [[[[  4]],

          [[ 10]]],


         [[[  3]],

          [[  2]]]]]])

In [62]:
np.expand_dims #--> untuk nambah 1dimensi, bisa diawal, tengah, dst

<function numpy.expand_dims(a, axis)>

In [63]:
np_array_a1[:]

array([2, 4, 6, 8])

In [64]:
np_array_a1[2:]

array([6, 8])

In [65]:
np_array_a1[:, np.newaxis]

array([[2],
       [4],
       [6],
       [8]])

In [67]:
np.expand_dims(np_array_a1, axis=0)

array([[2, 4, 6, 8]])

In [68]:
np.expand_dims(np_array_a1, axis=1)

array([[2],
       [4],
       [6],
       [8]])

In [69]:
np_array_a1[:, None]

array([[2],
       [4],
       [6],
       [8]])

In [72]:
np_array_a1[None,:, None, None] #--> simpel tapi tidak bisa diketahui oleh next coder

array([[[[2]],

        [[4]],

        [[6]],

        [[8]]]])

In [71]:
np_array_a1[np.newaxis,:,np.newaxis,np.newaxis] #--> lebih panjang tapi lebih dipahami

array([[[[2]],

        [[4]],

        [[6]],

        [[8]]]])

In [74]:
np_array_a1

array([2, 4, 6, 8])

In [78]:
size = np_array_a2.size
new_size = 10
np.append(np_array_a2, np.zeros(new_size - size)).reshape((2,5))

array([[1., 2., 3., 4., 5.],
       [6., 0., 0., 0., 0.]])

In [77]:
np_array_c1 = np.arange(0, 1.8, 0.2)
print(np_array_c1, np_array_c1.shape, np_array_c1.size)

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6] (9,) 9


In [79]:
# cari median
# median --> nilai tengah --> n=9, nilai tengah index ke-4
# cari tau n, dengan cara len()
# n // 2 pake double slash biar pembulatan kebawah (bentuknya integer)

In [82]:
n = np_array_c1.shape[0]
print("number of item:", n)

med = np_array_c1[n //2]
print('median:', med)

number of item: 9
median: 0.8


In [83]:
list_array_b2 = np_array_b2.tolist()
print(list_array_b2, type(list_array_b2))

[[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]] <class 'list'>


In [84]:
list_array_b2[0]

[0.1, 0.2, 0.3]

In [85]:
list_array_b2[0][:2], list_array_b2[1][:2]

([0.1, 0.2], [0.4, 0.5])

In [86]:
np_array_b2[:] #di axis pertama

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6]])

In [87]:
np_array_b2[:, :2] #: tanda axis pertama, :2 tanda axis kedua

array([[0.1, 0.2],
       [0.4, 0.5]])

In [88]:
np_array_b2[:,0]

array([0.1, 0.4])

In [89]:
np_array_b2[:,1]

array([0.2, 0.5])

In [90]:
np_array_b2[:,0], np_array_b2[:,2]

(array([0.1, 0.4]), array([0.3, 0.6]))

In [91]:
np_array_b2[0,:], np_array_b2[0,2]

(array([0.1, 0.2, 0.3]), 0.3)

In [92]:
np_array_b2[0], np_array_b2[0,2]

(array([0.1, 0.2, 0.3]), 0.3)

In [99]:
np_array_b2[:,[2]]

array([[0.3],
       [0.6]])

In [100]:
np_array_b2[:, [0,2]]

array([[0.1, 0.3],
       [0.4, 0.6]])

In [102]:
np_array_b2[:,::2]

array([[0.1, 0.3],
       [0.4, 0.6]])

In [101]:
np_array_b2[0], np_array_b2[0,], np_array_b2[0,:], np_array_b2[0, [0,1,2]]

(array([0.1, 0.2, 0.3]),
 array([0.1, 0.2, 0.3]),
 array([0.1, 0.2, 0.3]),
 array([0.1, 0.2, 0.3]))

In [103]:
np_array_c2 = np_array_a3.reshape((3,12))
print(np_array_c2)

[[  9   3   1   5   1   3   2   3   4  10   3   2]
 [ 19   3   1  50  11   3  12  13   4  10   3   2]
 [100   3   1   5   1   3   2   3   4  10   3   2]]


In [104]:
np_array_c2[:,::2]

array([[  9,   1,   1,   2,   4,   3],
       [ 19,   1,  11,  12,   4,   3],
       [100,   1,   1,   2,   4,   3]])

In [105]:
np_array_c2[np_array_c2 % 3 == 0] #--> yang habis dibagi 3 saja (indexing dengan condition)

array([ 9,  3,  3,  3,  3,  3,  3, 12,  3,  3,  3,  3,  3])

In [106]:
np_array_a1[True]

array([[2, 4, 6, 8]])

In [107]:
np_array_c2 % 3 == 0

array([[ True,  True, False, False, False,  True, False,  True, False,
        False,  True, False],
       [False,  True, False, False, False,  True,  True, False, False,
        False,  True, False],
       [False,  True, False, False, False,  True, False,  True, False,
        False,  True, False]])

In [118]:
np.concatenate((np_array_c2),(np_array_c2),(np_array_c2)) #--> too fast

TypeError: only integer scalar arrays can be converted to a scalar index

In [111]:
np_array_c2 / np_array_c2

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [112]:
np_array_c2 + np_array_c2

array([[ 18,   6,   2,  10,   2,   6,   4,   6,   8,  20,   6,   4],
       [ 38,   6,   2, 100,  22,   6,  24,  26,   8,  20,   6,   4],
       [200,   6,   2,  10,   2,   6,   4,   6,   8,  20,   6,   4]])

In [115]:
np_array_c2 * 2

array([[ 18,   6,   2,  10,   2,   6,   4,   6,   8,  20,   6,   4],
       [ 38,   6,   2, 100,  22,   6,  24,  26,   8,  20,   6,   4],
       [200,   6,   2,  10,   2,   6,   4,   6,   8,  20,   6,   4]])

In [116]:
np_array_c2 + 2

array([[ 11,   5,   3,   7,   3,   5,   4,   5,   6,  12,   5,   4],
       [ 21,   5,   3,  52,  13,   5,  14,  15,   6,  12,   5,   4],
       [102,   5,   3,   7,   3,   5,   4,   5,   6,  12,   5,   4]])

In [117]:
np_array_c2 + np_array_c2 [0]

array([[ 18,   6,   2,  10,   2,   6,   4,   6,   8,  20,   6,   4],
       [ 28,   6,   2,  55,  12,   6,  14,  16,   8,  20,   6,   4],
       [109,   6,   2,  10,   2,   6,   4,   6,   8,  20,   6,   4]])

In [121]:
np_array_c2

array([[  9,   3,   1,   5,   1,   3,   2,   3,   4,  10,   3,   2],
       [ 19,   3,   1,  50,  11,   3,  12,  13,   4,  10,   3,   2],
       [100,   3,   1,   5,   1,   3,   2,   3,   4,  10,   3,   2]])

In [120]:
np_array_c2.max()

100

In [122]:
print(np_array_c2.max())
print(np_array_c2.max(axis=1)) # max by row

100
[ 10  50 100]


In [123]:
print(np_array_c2.max())
print(np_array_c2.max(axis=0)) # max by column

100
[100   3   1  50  11   3  12  13   4  10   3   2]


In [127]:
print(np_array_c2.max(axis=1, keepdims=True)) # sustain its dimension

[[ 10]
 [ 50]
 [100]]


In [128]:
print(np_array_c2.max(axis=0, keepdims=True)) # sustain its dimension

[[100   3   1  50  11   3  12  13   4  10   3   2]]


In [129]:
np_array_a2

array([[1, 2, 3],
       [4, 5, 6]])

In [131]:
np.dot(np_array_a2, np_array_a2) #--> perlu pakai transpose

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [132]:
np_array_a2.transpose(),np_array_a2.T

(array([[1, 4],
        [2, 5],
        [3, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [133]:
np.dot(np_array_a2, np_array_a2.T)

array([[14, 32],
       [32, 77]])

In [135]:
np_array_a2.dot(np_array_a2.T)

array([[14, 32],
       [32, 77]])

In [136]:
np.matmul(np_array_a2, np_array_a2.T) --> lebih efisien

array([[14, 32],
       [32, 77]])

In [137]:
np_array_a2.flatten()

array([1, 2, 3, 4, 5, 6])

In [138]:
np_array_a3.flatten()

array([  9,   3,   1,   5,   1,   3,   2,   3,   4,  10,   3,   2,  19,
         3,   1,  50,  11,   3,  12,  13,   4,  10,   3,   2, 100,   3,
         1,   5,   1,   3,   2,   3,   4,  10,   3,   2])

In [139]:
np.random

<module 'numpy.random' from 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\numpy\\random\\__init__.py'>

In [140]:
np.random.randint() #--> bisa dibuat low berapa dan high berapa

TypeError: randint() takes at least 1 positional argument (0 given)

In [141]:
np.random.randint(10, size=(5,5))

array([[1, 7, 8, 3, 9],
       [9, 2, 0, 8, 3],
       [5, 9, 7, 7, 1],
       [3, 7, 3, 1, 8],
       [9, 7, 9, 6, 0]])

In [142]:
np.random.randint(10, 100, size=(5,5)) #--> 10 low dan high at 100

array([[31, 29, 89, 21, 33],
       [96, 42, 52, 44, 88],
       [94, 99, 24, 11, 73],
       [45, 36, 10, 18, 25],
       [27, 98, 97, 90, 29]])

In [143]:
np.random.randint(10, 100, size=(2,2,3)) #--> 10 low dan high at 100

array([[[25, 71, 55],
        [16, 66, 74]],

       [[53, 77, 87],
        [95, 66, 31]]])